### ISSUE TITLE
Use it with versioned css files?

### ISSUE THREAD

**Issue by janstieler** [dbergey/Reloadr#9]
Hi,
is it also possible to use it with versioned css files?
E.G: `path/to/css/style.css?version=1521023277`

This css is generated from my scss files and the number is often changing. 

Cheers

**Comment by dbergey** [comment]
Probably not. This library is deprecated anyway. I’ll update the readme soon.

**Comment by janstieler** [comment]
Hi,
okay thanks for your reply!
